---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: public-inbox-data
  namespace: communishift-public-inbox-poc
spec:
  accessModes:
    # EBS gp3-csi RWO is fine because both containers run in one pod.
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: gp3-csi
